namespace: myapp
output:
  file_path: ./Desarrollo-seguro-entrega-final.csv
  format: CSV
working_dir: .
strict: true
language: ES
file_size_limit: false
apk:
  include:
    - glob(**/*.apk)
sast:
  include:
    - .
  exclude:
    - glob(**/node_modules/**)
    - glob(**/test/**)
sca:
  include:
    - .
  exclude:
    - glob(**/test/**)
