namespace: myapp
output:
  file_path: ./Desarrollo-seguro-entrega-final.csv
  format: CSV
working_dir: .
strict: true
language: ES
file_size_limit: false
checks:
  - F006
  - F007
  - F013
  - F126
  - F032
  - F014
  - F048
sast:
  include:
    - .
  exclude:
    - ./website/test.php
  recursion-limit: 1000
sca:
  include:
    - .
  exclude:
    - ./website/test.php
