namespace: myapp
output:
  file_path: ./Desarrollo-seguro-entrega-final.csv
  format: CSV
working_dir: .
strict: true
language: ES
file_size_limit: false
sast:
  include:
    - .
  exclude:
    - ./website/test.php
  recursion-limit: 1000
sca:
  include:
    - .
  exclude:
    - ./website/test.php
